### ISSUE TITLE
Missing ticks reported by output_mon_lens

### ISSUE THREAD

**Issue by lplana** [SpiNNakerManchester/SpiNNaker_PDP2#16]
With the latest changes, the number of missing ticks reported by 'output_mon_lens' has increased significantly.

This appears to be a problem of SDP messages being dropped, not a problem with actual computation on SpiNNaker.

A delay was inserted before sending data to the host to try to reduce the problem [process_t.c/line 308]. This seems to be working but should only be a temporary measure. We may need to stop using output_mon_lens and use a different approach to report data.

**Comment by alan-stokes** [comment]
Hi Luis, if your code on host is python, i can confirm thats what we had going on with the data extractor. its why we're looking into a c++ libuary to use with the python to bypass the issue. its basically that python is too slow and you cant easily expand the o's sdp message buffer to handle this.

**Comment by lplana** [comment]
Pull request #29 eliminates the use of __output_mon_lens__ and makes this issue irrelevant.
